# Generated by Django 4.0.6 on 2022-07-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patientclinicaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('height_date', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('weight_date', models.DateTimeField()),
                ('bp', models.PositiveIntegerField()),
                ('bp_date', models.DateTimeField()),
                ('heartrate', models.PositiveIntegerField()),
                ('heartrate_date', models.DateTimeField()),
                ('pat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labuser.patient')),
            ],
        ),
    ]
