# Generated by Django 4.0.6 on 2022-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
