# Generated by Django 4.0.6 on 2022-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labuser', '0002_alter_patient_gender_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinicaldata',
            name='bp_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientclinicaldata',
            name='heartrate_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientclinicaldata',
            name='height_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientclinicaldata',
            name='weight_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
