# Generated by Django 4.0.6 on 2022-07-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labuser', '0003_alter_patientclinicaldata_bp_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientclinicaldata',
            old_name='pat',
            new_name='Patient',
        ),
    ]
